# Generated by Django 3.2.9 on 2021-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=200)),
                ('billing_firstname', models.CharField(max_length=50, null=True)),
                ('billing_lastname', models.CharField(max_length=50, null=True)),
                ('billing_address', models.CharField(max_length=200)),
                ('billing_address_complement', models.CharField(max_length=200, null=True)),
                ('billing_zipcode', models.IntegerField()),
                ('billing_city', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
    ]
