# Generated by Django 3.2.9 on 2021-11-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='billing_zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='marketplace',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
