# Generated by Django 3.2.9 on 2021-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_firstname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='billing_lastname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
